import type { Metadata } from "next";
import { Geist, Noto_Sans_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const NotoSansMono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${NotoSansMono.variable} antialiased`}
      >
        <p className="text-xs font-mono fixed top-4 left-4 font-bold">olcchi Gen</p>
        {children}
      </body>
    </html>
  );
}
